### ISSUE TITLE
chimpanzees, preview of DynamicHMC 2.0 API

### ISSUE THREAD

**Issue by tpapp** [StatisticalRethinkingJulia/DynamicHMCModels.jl#2]
@goedman I am continuing our discussion at https://github.com/tpapp/DynamicHMC.jl/issues/42 here.

First, I think that the new and refactored DynamicHMC, which will be 2.0, samples this model just fine.

Second, since you are one of the main users, I wanted to get early feedback on the new API, and perhaps an example is the best way to do that.

This is the code, it requires the development branch of DynamicHMC, and of course the data:
```julia
#####
##### IMPORTANT: API is WIP, make sure you use this on DynamicHMC#tp/major-api-rewrite-2.0
#####

using DynamicHMC, LogDensityProblems, TransformVariables, StatsFuns, Distributions,
    Parameters, CSV, DataFrames, Random, StanDump, StanRun, StanSamples, PGFPlotsX, StatsBase
import Flux

data = DataFrame(CSV.File("chimpanzees.csv"; delim = ';'))

Base.@kwdef struct Chimpanzees
    N_actors::Int
    pulled_left::Vector{Int}
    prosoc_left::Vector{Int}
    condition::Vector{Int}
    actor::Vector{Int}
end

function make_transformation(model::Chimpanzees)
    as((a = as(Vector, model.N_actors), bp = asℝ, bpC = asℝ))
end

stan_data = (N = length(data.pulled_left), P = data.prosoc_left, C = data.condition,
             L = data.pulled_left, N_chimps = maximum(data.actor), chimp = data.actor)
stan_model = StanModel(joinpath(pwd(), "chimpanzees.stan"))
# just one chain from Stan
stan_chain = first(stan_sample(stan_model, stan_data, 1))
stan_samples = read_samples(first(stan_chain))

model = Chimpanzees(; N_actors = maximum(data.actor), pulled_left = data.pulled_left,
                    prosoc_left = data.prosoc_left, condition = data.condition,
                    actor = data.actor)

function (model::Chimpanzees)(θ)
    @unpack a, bp, bpC = θ
    @unpack pulled_left, prosoc_left, condition, actor = model
    ℓ_likelihood = mapreduce(+, actor, condition, prosoc_left,
                             pulled_left) do actor, condition, prosoc_left, pulled_left
                                 p = logistic(a[actor] + (bp + bpC * condition) * prosoc_left)
                                 logpdf(Bernoulli(p), pulled_left)
                             end
    P = Normal(0, 10)
    ℓ_prior = logpdf(P, bpC) + logpdf(P, bp) + sum(a -> logpdf(P, a), a)
    ℓ_prior + ℓ_likelihood
end

P = TransformedLogDensity(make_transformation(model), model)
∇P = ADgradient(:Flux, P)
results = mcmc_with_warmup(Random.GLOBAL_RNG, ∇P, 1000)
posterior = P.transformation.(results.chain)

function comparison_plot(xlabel, dhmc_values, stan_values)
    @pgf Axis({ xlabel = xlabel, ylabel = "ecdf", legend_pos = "south east" },
              Plot({ no_marks, red }, Table(ecdf(dhmc_values))),
              LegendEntry("DynamicHMC"),
              Plot({ no_marks, blue }, Table(ecdf(stan_values))),
              LegendEntry("Stan"))
end

###
### plots will show up interactively
###

comparison_plot("bp", getfield.(posterior, :bp), stan_samples.bp)
comparison_plot("bpC", getfield.(posterior, :bpC), stan_samples.bpc)
p7 = [comparison_plot("a[$(i)]", getindex.(getfield.(posterior, :a), Ref(i)),
                      stan_samples.a_chimp[i, :]) for i in 1:7]

p7[1]
p7[2]
p7[3]
p7[4]
p7[5]
p7[6]
p7[7]

NUTS_statistics(results.tree_statistics)

EBFMI(results.tree_statistics)
```

**Comment by tpapp** [comment]
And the comparison of posterior ECDFs from Stan and DynamicHMC 2.0:
![bp](https://user-images.githubusercontent.com/84122/62792567-dbcaac00-bacf-11e9-9ce6-7c1bb995d60e.png)
![bpC](https://user-images.githubusercontent.com/84122/62792573-df5e3300-bacf-11e9-815a-a3029ab85695.png)
![a1](https://user-images.githubusercontent.com/84122/62792590-e9803180-bacf-11e9-849e-dbb2c3ff6494.png)
![a2](https://user-images.githubusercontent.com/84122/62792595-ec7b2200-bacf-11e9-8232-7ddfc6029bd8.png)
![a3](https://user-images.githubusercontent.com/84122/62792602-ef761280-bacf-11e9-929c-986dc383cb9b.png)
![a4](https://user-images.githubusercontent.com/84122/62792610-f3099980-bacf-11e9-8265-0e90eebae8c1.png)
![a5](https://user-images.githubusercontent.com/84122/62792620-f7ce4d80-bacf-11e9-9385-0d4f75aec855.png)
![a6](https://user-images.githubusercontent.com/84122/62792628-fac93e00-bacf-11e9-90a2-b092a888e275.png)
![a7](https://user-images.githubusercontent.com/84122/62792632-fe5cc500-bacf-11e9-94e7-65a797da467c.png)

**Comment by goedman** [comment]
Thank you! I will study the new API this weekend and work through the SR models next week.

**Comment by goedman** [comment]
Hi Tamas,

Once again I am very impressed by your API updates and the results this model now produces. No problem getting the branch up and running and indeed for this 'difficult' model spot on! 

You asked for feedback on the updated API. I really like the sequence of the steps as shown in your example. Both the use of `Base.@kwdef` and later on the model definition are clean and succinct.

Mildly confusing is maybe the implicit definition of in this example θ which happens in `make_transformation()` (but quickly I started to think of it as define_parameters_transformation and later on (to extract the posterior) `transformation` as inverse_transformation.

I noticed in mcmc.jl that `warmup()` returns `nothing, WarmupState(Q, κ, ϵ)`. Previously I had experimented a bit with Optim to get that initial optimum. I think it basically is the mode that in StatisticalRethinking is found with R's quap(). I sometimes wonder if it makes sense to be able to split `mcmc_with_warmup()` in 3 steps: `finding initial optimum`, a second step that would return the warmup samples and a final step returning the samples..

Next week I'll do all the other models and last time around that was an eye opener for me!

Thanks again for this great package and update.

Best,Rob

**Comment by tpapp** [comment]
Thanks for the feedback.

I could not find `quap()` in R, is it in some package?

The way warmup currently works is via
```julia
result, next_warmup_state = warmup(sampling_logdensity, warmup_stage, warmup_state)
```
Some stages, notably optimization and stepsize search, have no results *per se*, hence the `nothing`. The next position and stepsize are in `next_warmup_state`.

Note that I am still working on the API and the core sampler, so please keep this in mind before redoing all of the StatisticalRethinking code. Also, I plan to make everything Zygote-friendly before release.

**Comment by goedman** [comment]
`quap()` is a function in the `rethinking` R package. `rethinking` uses 2 functions for inference. The first half of the book uses a quadratic approximation using the mode as mean and  `std(observations, mean=mode)`. 

A second function, `ulam()`, translates the models to the Stan language. In the 2nd edition there is some more emphasis on also learning the Stan language. I plan to provide most models using StanSample in StanModels, but in StatisticalRethinking package itself my plan is to show all results based on DynamicHMC. In DynamicHMCModels I might occasionally use more advanced formulations, e.g. in your example `map reduce`.

It's interesting that when running your example several times sometimes it warns that the initial local optimum can't be found and at other times it can. Either way, the mcmc results are always fine!

I realize the API is still being updated, which is fine. I'm happy to track those.

**Comment by tpapp** [comment]
Thanks for the information.

In the meantime, I merged the above branch to `master`. The API is actually not likely to change much, so if you want to, go ahead converting your code and testing your models. If you notice problems, please open an issue and I will help investigate.

In particular, comparing the stepsize from DynamicHMC to eg Stan would be helpful. You just extract the `ϵ` from the `NamedTuple` returned by `mcmc_with_warmup`.
